kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta2
metadata:
  name: example
  namespace: selenium-infra
  uid: d8c33ba6-c6ed-4abc-ba61-d037d0cf9a8a
  resourceVersion: '16580282'
  creationTimestamp: '2022-01-03T12:18:00Z'
  managedFields:
    - manager: Mozilla
      operation: Update
      apiVersion: autoscaling/v2beta2
      time: '2022-01-03T12:18:00Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          'f:maxReplicas': {}
          'f:metrics': {}
          'f:minReplicas': {}
          'f:scaleTargetRef':
            'f:apiVersion': {}
            'f:kind': {}
            'f:name': {}
    - manager: kube-controller-manager
      operation: Update
      apiVersion: autoscaling/v1
      time: '2022-01-03T12:18:30Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            'f:autoscaling.alpha.kubernetes.io/conditions': {}
            'f:autoscaling.alpha.kubernetes.io/current-metrics': {}
        'f:status':
          'f:currentReplicas': {}
          'f:desiredReplicas': {}
          'f:lastScaleTime': {}
      subresource: status
spec:
  scaleTargetRef:
    kind: DeploymentConfig
    name: selenium-node-chrome
    apiVersion: apps.openshift.io/v1
  minReplicas: 2
  maxReplicas: 20
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 10
status:
  lastScaleTime: '2022-01-03T12:18:15Z'
  currentReplicas: 4
  desiredReplicas: 4
  currentMetrics:
    - type: Resource
      resource:
        name: memory
        current:
          averageValue: '153353216'
          averageUtilization: 7
  conditions:
    - type: AbleToScale
      status: 'True'
      lastTransitionTime: '2022-01-03T12:18:15Z'
      reason: ScaleDownStabilized
      message: >-
        recent recommendations were higher than current one, applying the
        highest recent recommendation
    - type: ScalingActive
      status: 'True'
      lastTransitionTime: '2022-01-03T12:18:30Z'
      reason: ValidMetricFound
      message: >-
        the HPA was able to successfully calculate a replica count from memory
        resource utilization (percentage of request)
    - type: ScalingLimited
      status: 'False'
      lastTransitionTime: '2022-01-03T12:18:30Z'
      reason: DesiredWithinRange
      message: the desired count is within the acceptable range
