kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  name: selenium-hub
  namespace: sele
  uid: 0bd3fd85-56b2-44a6-adce-348211ab64c2
  resourceVersion: '16462172'
  generation: 11
  creationTimestamp: '2021-12-27T10:53:45Z'
  labels:
    selenium-hub: master
  managedFields:
    - manager: kubectl-create
      operation: Update
      apiVersion: apps.openshift.io/v1
      time: '2021-12-27T10:53:45Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:labels':
            .: {}
            'f:selenium-hub': {}
        'f:spec':
          'f:replicas': {}
          'f:selector':
            .: {}
            'f:type': {}
          'f:strategy':
            'f:activeDeadlineSeconds': {}
            'f:rollingParams':
              .: {}
              'f:intervalSeconds': {}
              'f:maxSurge': {}
              'f:maxUnavailable': {}
              'f:timeoutSeconds': {}
              'f:updatePeriodSeconds': {}
            'f:type': {}
          'f:template':
            .: {}
            'f:metadata':
              .: {}
              'f:creationTimestamp': {}
              'f:labels':
                .: {}
                'f:type': {}
              'f:name': {}
            'f:spec':
              .: {}
              'f:containers':
                .: {}
                'k:{"name":"master"}':
                  .: {}
                  'f:env':
                    'k:{"name":"GRID_UNREGISTER_IF_STILL_DOWN_AFTER"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"GRID_CLEAN_UP_CYCLE"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"POOL_MAX"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"GRID_MAX_SESSION"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"GRID_NEW_SESSION_WAIT_TIMEOUT"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"GRID_TIMEOUT"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    .: {}
                    'k:{"name":"JAVA_OPTS"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"GRID_NODE_POLLING"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"GRID_BROWSER_TIMEOUT"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"GRID_JETTY_MAX_THREADS"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                  'f:imagePullPolicy': {}
                  'f:name': {}
                  'f:ports':
                    .: {}
                    'k:{"containerPort":4444,"protocol":"TCP"}':
                      .: {}
                      'f:containerPort': {}
                      'f:protocol': {}
                  'f:resources': {}
                  'f:terminationMessagePath': {}
                  'f:terminationMessagePolicy': {}
              'f:dnsPolicy': {}
              'f:restartPolicy': {}
              'f:schedulerName': {}
              'f:securityContext': {}
              'f:terminationGracePeriodSeconds': {}
          'f:triggers': {}
    - manager: Mozilla
      operation: Update
      apiVersion: apps.openshift.io/v1
      time: '2022-01-03T08:07:25Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          'f:template':
            'f:spec':
              'f:containers':
                'k:{"name":"master"}':
                  'f:image': {}
                  'f:resources':
                    'f:limits':
                      .: {}
                      'f:cpu': {}
                      'f:memory': {}
    - manager: openshift-controller-manager
      operation: Update
      apiVersion: apps.openshift.io/v1
      time: '2022-01-03T08:07:28Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          'f:updatedReplicas': {}
          'f:readyReplicas': {}
          'f:conditions':
            .: {}
            'k:{"type":"Available"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:lastUpdateTime': {}
              'f:message': {}
              'f:status': {}
              'f:type': {}
            'k:{"type":"Progressing"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:lastUpdateTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
          'f:details':
            .: {}
            'f:causes': {}
            'f:message': {}
          'f:replicas': {}
          'f:availableReplicas': {}
          'f:observedGeneration': {}
          'f:unavailableReplicas': {}
          'f:latestVersion': {}
      subresource: status
spec:
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 600
      maxUnavailable: 25%
      maxSurge: 25%
    resources: {}
    activeDeadlineSeconds: 21600
  triggers:
    - type: ConfigChange
  replicas: 1
  revisionHistoryLimit: 10
  test: false
  selector:
    type: selenium-hub
  template:
    metadata:
      name: selenium-hub
      creationTimestamp: null
      labels:
        type: selenium-hub
    spec:
      containers:
        - name: master
          image: 'selenium/hub:4.1.0-20211123'
          ports:
            - containerPort: 4444
              protocol: TCP
          env:
            - name: JAVA_OPTS
              value: '-Xmx512m'
            - name: POOL_MAX
              value: '30000'
            - name: GRID_NEW_SESSION_WAIT_TIMEOUT
              value: '30'
            - name: GRID_JETTY_MAX_THREADS
              value: '100'
            - name: GRID_NODE_POLLING
              value: '150'
            - name: GRID_CLEAN_UP_CYCLE
              value: '300'
            - name: GRID_TIMEOUT
              value: '300'
            - name: GRID_BROWSER_TIMEOUT
              value: '30'
            - name: GRID_MAX_SESSION
              value: '3'
            - name: GRID_UNREGISTER_IF_STILL_DOWN_AFTER
              value: '500'
          resources:
            limits:
              cpu: 1k
              memory: 2Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
status:
  observedGeneration: 11
  details:
    message: config change
    causes:
      - type: ConfigChange
  availableReplicas: 1
  unavailableReplicas: 1
  latestVersion: 3
  updatedReplicas: 1
  conditions:
    - type: Available
      status: 'True'
      lastUpdateTime: '2021-12-29T14:03:10Z'
      lastTransitionTime: '2021-12-29T14:03:10Z'
      message: Deployment config has minimum availability.
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2022-01-03T08:07:28Z'
      lastTransitionTime: '2022-01-03T08:07:28Z'
      reason: ReplicationControllerUpdated
      message: replication controller "selenium-hub-3" is progressing
  replicas: 2
  readyReplicas: 1
