apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ubuntu
  name: ubuntu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ubuntu
    spec:
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/containertest/maven-custum-image:latest
        name: ubuntu
        command: ["/bin/sleep", "3650d"]
        resources: {}
